apiVersion: apps/v1
kind: Deployment
metadata:
  name: refer-friends
  annotations:
    ves.io/sites: ves-io-system/hk2-hkg
  labels:
    app: refer-friends
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refer-friends
      version: v1
  template:
    metadata:
      labels:
        app: refer-friends
        version: v1
    spec:
      containers:
        - image: reg.edgecnf.com/fintech/arcadia-refer-friends:v2.0
          imagePullPolicy: IfNotPresent
          name: refer-friends
          env:
            - name: service_name
              value: refer-friends
          name: refer-friends
          ports:
            - containerPort: 9080
              protocol: TCP
        - name: nginx-sc
          image: reg.edgecnf.com/apps/nginx-unpriv:v1.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9090
          volumeMounts:
          - name: default-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
        - name: apigw-refer-friends
          image: reg.edgecnf.com/apps/arcadia-apigw:v2.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4010
          volumeMounts:
          - name: api-gw-rf
            mountPath: /usr/src/prism/api-gw.json
            subPath: api-gw.json
      volumes:
        - name: default-conf
          configMap:
             name: sc-nginx-default-conf-9090-rf-cm
        - name: api-gw-rf
          configMap:
             name: api-gw-rf.json


