apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-nginx-default-conf-9090-rf-cm
  annotations:
    ves.io/sites: ves-io-system/hk2-hkg
data:
  default.conf: |
    server {
    listen       9090;
    #server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    #location / {
    #    root   /usr/share/nginx/html;
    #    index  index.html index.htm;
    #}

    #location /__imp_apg__/ {
    #  proxy_pass https://dip.zeronaught.com;
    #}

    location / {
        # DeviceID JS
        sub_filter '</head>' '<script async defer src="https://us.gimp.zeronaught.com/__imp_apg__/js/volt-f5_apac_sp_yhsgmcye-3a06b9c8.js" id="_imp_apg_dip_" _imp_apg_cid_="volt-f5_apac_sp_yhsgmcye-3a06b9c8" _imp_apg_api_domain_="https://us.gimp.zeronaught.com"></script></head>';


        # proxy to upstream applications
        proxy_pass http://127.0.0.1:9080;
        proxy_set_header Host $http_host;
        #proxy_set_header Host shop.foobz.com.au;

        # don't use http 1.0 so keepalive enabled by default
        proxy_http_version 1.1;

        # prevent client from closing keepalive
        proxy_set_header Connection "";

        # don't need timeouts for process to process communication
        # (why complicate things with this MITM proxy? let client timeout)
        proxy_send_timeout 86400s;
        proxy_read_timeout 86400s;

        # don't write client body to docker file system
        proxy_request_buffering off;
    }


    location /api/v1 {
       proxy_pass http://127.0.0.1:4010/api/v1;
       #proxy_set_header Host $http_host;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
       proxy_send_timeout 86400s;
       proxy_read_timeout 86400s;
       proxy_request_buffering off;
    }


    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}

    }
