apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    ves.io/proxy-type: HTTP_PROXY
    ves.io/app_type: arcadia-ocp
  labels:
    app: backend
    service: backend
spec:
  ports:
  - name: backend-80
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: backend
