apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xc-svc-discovery-cr
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - nodes/proxy
  - namespaces
  verbs: ["get", "list", "watch"]
