apiVersion: v1
kind: Service
metadata:
  name: ver-dns
  namespace: ves-system
  labels:
    app: ver
spec:
  ports:
    - name: "ver-dns-udp"
      protocol: UDP
      port: 53
      targetPort: 53
    - name: "ver-dns-tcp"
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
      app: ver
