apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: reg.edgecnf.com/fintech/arcadia-frontend:v2.0-ocp
          imagePullPolicy: IfNotPresent
          name: frontend
          env:
            - name: service_name
              value: frontend
          name: frontend
          ports:
            - containerPort: 9080
              protocol: TCP
        - name: nginx-sc
          image: reg.edgecnf.com/ngx/ngx-plus:v3.0-unpriv
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
          volumeMounts:
          - name: default-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
        - name: apigw-trading
          image: reg.edgecnf.com/apps/arcadia-apigw:v2.3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4010
          volumeMounts:
          - name: api-gw
            mountPath: /usr/src/prism/api-gw.json
            subPath: api-gw.json
        - name: apigw-loadgen
          image: reg.edgecnf.com/apps/newman:2.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: fe-to-money-backend-referfriends-postman
            mountPath: /tmp/fe-to-money-backend-referfriends-postman.json
            subPath: fe-to-money-backend-referfriends-postman.json
          - name: run-apigen-fe
            mountPath: /tmp/run-apigw-loadgen.sh
            subPath: run-apigw-loadgen.sh
      volumes:
        - name: default-conf
          configMap:
             name: sc-nginx-default-conf-9090-fe-cm
        - name: api-gw
          configMap:
             name: api-gw-fe.json
        - name: fe-to-money-backend-referfriends-postman
          configMap:
             name: fe-to-money-backend-referfriends-postman.json
        - name: run-apigen-fe
          configMap:
             name: run-apigen-fe.sh
             defaultMode: 0777
