apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    ves.io/proxy-type: HTTP_PROXY
    ves.io/app_type: arcadia-ocp
    ves.io/sites: ves-io-system/me1-mel
  labels:
    app: frontend
spec:
  ports:
  - name: frontend-80
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: frontend
